services:
  front:
    image: front-dev
    build:
      context: ./todo-frontend/ # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: front-dev # This will name the container front-dev

  back:
    image: backend-dev
    build:
      context: ./todo-backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    ports:
      - 3001:3001
    depends_on:
      - "mongo"
      - "redis"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "front"
      - "back"
    ports:
      - 8080:80
    container_name: reverse-proxy


  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
      
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes: 
      - ./todo-backend/redis_data:/data
    ports:
      - 6379:6379
      
volumes:
  mongo_data:
